Feature/TR-765/load test taker response in audio PCI
oat-sa/extension-tao-itemqti-pci pull request #221
Opened 2021-03-18 15:16 UTC by jsconan

Related to: https://oat-sa.atlassian.net/browse/TR-775

Make sure the `audioRecording` PCI can accept a serialized state or a response as a state.

When reviewing the response, the state is restored from a serialized version, and the object contains an additional level.

How to test:
- run the unit tests (`cd tao/views/build && npx grunt connect:dev qtiitempcitest`)
- see the main PR on taoOutcomeUI for a more complete test case

2021-03-19 07:25 UTC, btamas requested changes
Everything looks good, except migration script description.

2021-03-19 07:25 UTC, btamas commented on migrations/Version202103181527241465_qtiItemPci.php
> +        return 'Update Liquids interaction';
Wrong interaction name.

2021-03-19 07:53 UTC, jsconan commented on migrations/Version202103181527241465_qtiItemPci.php
> +        return 'Update Liquids interaction';
oops, good catch!

2021-03-19 16:24 UTC, btamas approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-03-22 08:54 UTC, anshul119 approved these changes
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-03-22 09:25 UTC, merged