fix: rename likertScale PCI to likert in order to be able to import and use it straight away
oat-sa/extension-tao-itemqti-pci pull request #395
Opened 2024-02-27 12:51 UTC by wazelin

Follow up to #394.

2024-02-28 08:22 UTC, oatymart requested changes
If creating this PCI to be distinct from the `dev/likertScaleInteraction`, we need to pick a properly unique identifier.

Also, we are missing a PHP registration script here. Was that intended?

2024-02-28 08:22 UTC, oatymart commented on views/js/pciCreator/ims/likertScaleInteraction/creator/tpl/markup.tpl
> +<div class="likertInteraction">
This identifier is already taken by `pciCreator/ims/likertConfig`. (That's _another_ version of the PCI, which never had an install script. I have no idea which environments it was ever added to. Also its version is 1.2.0)

If using this PR, we should either choose a brand new identifier, or delete `likertConfig`.

2024-02-28 08:22 UTC, oatymart commented on views/js/pciCreator/ims/likertScaleInteraction/runtime/css/likerInteraction.css
New file name is missing a `t`. I guess it won't be loadable?

2024-02-28 11:44 UTC, wazelin commented on views/js/pciCreator/ims/likertScaleInteraction/runtime/css/likerInteraction.css
Updated the PR reducing the number of changes.

2024-02-28 14:58 UTC, oatymart commented on views/js/pciCreator/ims/likertScaleInteraction/runtime/css/likerInteraction.css
Sorry, but the simple identifier renaming was not really enough. I've changed the folder names, and the tests (all references from `Scale` -> `Score`) to leave a place that is not unpleasant to work in.

I've also updated the installer & migration.

The good news is, it still works fine as either a fresh install, a TAO update, or a zip upload.

2024-02-28 20:42 UTC, wazelin commented
> Also, we are missing a PHP registration script here. Was that intended?

To be fair, I thought more of _replacing_ the old likertScale PCI with you new version. Just under a different ID.

Not sure that we actually need both of them in the codebase.

Hence the lack of a dedicated registration script.

But I can see you've already covered that bit. Clean job, as always! Thanks!

2024-02-28 22:39 UTC, oatymart commented
I re-tested the import of the zipped PCI from my original PR, and got it to work in a develop TAO. (The 15-minute FE cache was making me think I had errors before!)

So I'm fairly convinced we don't need this identifier change any more.

2024-02-29 06:09 UTC, wazelin commented
> we don't need this identifier change any more

That's nice. However, there's another problem we're working around with this change. This piece of code will still continue blocking the PCI in item authoring on the customer's environment.

https://github.com/oat-sa/extension-tao-deliver-connect/blob/master/model/FeatureFlag/FeatureFlagClientConfigHandler.php#L43

2024-02-29 14:17 UTC, oatymart commented
The identifier change was committed directly to #394

2024-02-29 14:17 UTC, closed without merging